# POST   http://localhost:4002/user
# Content-Type: application/json

# {
#     "name":"mercy anami",
#     "password":"12345",
#     "email":"mercy@gmail.com",
#     "contact":"038500080005"
# }

# GET  http://localhost:4002/comments

# POST  http://localhost:4002/comment
# Content-Type: application/json

# {
#     "name":"valeria muhembele",
#     "email":"muhembe@gmail.com",
#     "comment":"I got no feedback on my request please. try to respond to me"
# }

DELETE http://localhost:4002/deletecomment
Content-Type: application/json

{
    "id":"634490e1a30876d73352c09d"
}